# 2. Regression and model validation

*Describe the work you have done this week and summarize your learning.*

```{R echo = FALSE, results = "hide"}
library(GGally)
library(ggplot2)
```

```{R echo = FALSE}
learning2014 <- read.table("data/learning2014.txt", header = TRUE)
```


Dataset is including information for 166 participant for 7 different variables.

```{R echo = FALSE}
str(learning2014)
```

```{R echo = FALSE}
dim(learning2014)
```

Variables are having information about participants gender, age and points for cognitive test. There is also included information of attitudes towards statistics as also scoring for levels of thinking as surface, deep, and strategic approaches.

For dataset is remarkable notice dataset to be unbalance with participant gender. Variables are little different by gender, but are mostly behaving simalarly with each other. 

```{R echo = FALSE}
ggpairs(learning2014, mapping = aes(col=gender, alpha = 0.3), lower = list(combo = wrap("facethist", bins = 20)))
```

Regarding the general linear model to seek predictors for points in test, I choose to use attitude, deep approach and strategic approach to explain result. Only attitude was found to be significant predictor.

```{R echo = FALSE}
my_model <- lm(Points ~ attitude + deep + stra, data = learning2014)
summary(my_model)
```

After leaving out  strategic approach for ecxplainíng variable, deep approach were still not significant predictor as attitude remains significant.

```{R echo = FALSE}
my_model <- lm(Points ~ attitude, data = learning2014)
summary(my_model)
```

In final model there were only  attitude as explaining variable for points in test.

```{R echo = FALSE}
my_model <- lm(Points ~ attitude, data = learning2014)
summary(my_model)
```

As looking for data, it seems to be quite well distributed and there is no any significant outlieras in data.

```{R echo = FALSE}
par(mfrow =c(2,2))
plot(my_model,c(1,2,5))
```

